# Generated by Django 2.2 on 2021-06-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likecount',
            field=models.IntegerField(null=True),
        ),
    ]
