# Generated by Django 2.2 on 2021-06-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_auto_20210621_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likecount',
        ),
    ]
